#:kivy 1.10.0

BoxLayout:
    orientation: 'vertical'

    Label:
        text: '[b]00[/b]:00:[sup]00[/sup]'
        markup: True
        font_name: 'OpenSans'

    BoxLayout:
        height: 90
        orientation: 'horizontal'
        padding: 20
        spacing: 20
        Button:
            font_name: 'OpenSans'
            text: 'Start'
            font_size: 25
            bold: True
        Button:
    
    Label:
        id: time
        markup: True